#!/bin/bash
PYFILE="$PYFILE"
PYFILEC="${PYFILE%.py}.pyc"

echo "Compiling $PYFILE ..."
python3 -m compileall "$PYFILE"
if [ -f "__pycache__/$PYFILEC" ]; then
    mv "__pycache__/$PYFILEC" .
    rm -rf __pycache__
else
    echo "Error: Compilation failed"
    exit 1
fi
